#ifndef PROJECTS_DRAWING_RECOGNITION_DRAWING_PROGRAM_CONST_H_
#define PROJECTS_DRAWING_RECOGNITION_DRAWING_PROGRAM_CONST_H_

const int WINDOW_WIDTH = 800;
const int WINDOW_HEIGHT = 800;

#endif  // PROJECTS_DRAWING_RECOGNITION_DRAWING_PROGRAM_CONST_H_
