name: Drawing-program

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup environment
      working-directory: ./Drawing-program
      run: sudo apt-get install g++ cmake libXrandr-devel libXinerama-devel libXcursor-devel libXi-devel && mkdir Build

    - name: Configure CMake
      working-directory: ./Drawing-program/Build
      run: cmake ./..

    - name: Build
      working-directory: ./Drawing-program
      run: cmake --build .
  