name: Python

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 requests opencv-python scikit-image

    - name: Build
      working-directory: ./CNN-TF
      run: python ./main.py

    - name: Syntax checker
      working-directory: ./CNN-TF
      run: flake8 . --max-line-length 128
