name: Python

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.7'

    - name: Install modules
      run: sudo pip install requests

    - name: Build
      working-directory: ./CNN-TF
      run: python ./main.py

    - name: Syntax checker
      working-directory: ./CNN-TF
      run: sudo pip install flake8 && flake8 .
